// <auto-generated />
namespace example.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _237 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_237));
        
        string IMigrationMetadata.Id
        {
            get { return "201908181517374_237"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
